site_name: My Docs
nav:
  - Newline Test:
      - Baseline: "newline-test.md"
      - Trailing Newlines True: "newline-test-trailing-newlines-true.md"
      - Trailing Newlines False: "newline-test-trailing-newlines-false.md"
  - No Newline Test:
      - Baseline: "no-newline-test.md"
      - Trailing Newlines True: "no-newline-test-trailing-newlines-true.md"
      - Trailing Newlines False: "no-newline-test-trailing-newlines-false.md"
  - Code block test:
      - Code Block: "code-block.md"
  - Info test:
      - Info test: "info-test"
theme:
  name: material
markdown_extensions:
  - admonition
plugins:
  - include-markdown
  - search
